"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import cloudinary
import cloudinary.uploader
import cloudinary.api
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Em produção (Render), o credenciais.json não vai pro repositório (está no .gitignore).
# Se a variável GOOGLE_CREDENTIALS_JSON existir, gravamos o conteúdo no arquivo esperado.
_google_creds_json = os.environ.get('GOOGLE_CREDENTIALS_JSON')
if _google_creds_json:
    _creds_path = BASE_DIR / os.environ.get('GOOGLE_SHEETS_CREDENTIALS_FILE', 'credenciais.json')
    if not _creds_path.exists():
        _creds_path.write_text(_google_creds_json, encoding='utf-8')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')

CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]


# Application definition

INSTALLED_APPS = [
    'core.apps.MongoAdminConfig',
    'core.apps.MongoAuthConfig',
    'core.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'obras',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'obras' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': os.environ['MONGODB_DB_NAME'],
        'HOST': os.environ['MONGODB_URI'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
# Quando logar, vai para a rota chamada 'inicio' (que é o seu dashboard)
LOGIN_REDIRECT_URL = 'inicio'

# Quando deslogar, também volta para o 'inicio'
LOGOUT_REDIRECT_URL = 'inicio'

# Onde fica a página de login
LOGIN_URL = 'login'

# --- CONFIGURAÇÃO DE SESSÃO ---

# TESTE: sessão dura 2 minutos (120 segundos) — lembrar de voltar para 3600 depois do teste
SESSION_COOKIE_AGE = 120

# Muito importante: toda vez que o usuário clica em algo, o cronômetro volta para 1 hora.
# Isso garante que a sessão só caia por INATIVIDADE real.
SESSION_SAVE_EVERY_REQUEST = True

# Garante que, se ele fechar o navegador, a sessão também seja encerrada por segurança.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Configuração do Cloudinary para o upload de imagens
cloudinary.config(
  cloud_name = os.environ['CLOUDINARY_CLOUD_NAME'],
  api_key = os.environ['CLOUDINARY_API_KEY'],
  api_secret = os.environ['CLOUDINARY_API_SECRET'],
  secure = True
)